printWidth: 120
tabWidth: 2
useTabs: false
semi: false
singleQuote: false
trailingComma: none
bracketSpacing: true
arrowParens: always
bracketSameLine: false
htmlWhitespaceSensitivity: ignore
svelteBracketNewLine: true
plugins:
  - "prettier-plugin-svelte"
